version: '3'

services:

  main:
    image: vfarcic/go-demo
    environment:
      - DB=db
    networks:
      - proxy
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/demo
        - com.df.port=8080
        - com.df.alertName=mem_limit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=5s
        - com.df.scaleMin=2
        - com.df.scaleMax=4
      resources:
        reservations:
          memory: 5M
        limits:
          memory: 10M

  db:
    image: mongo
    networks:
      - proxy
    deploy:
      resources:
        reservations:
          memory: 40M
        limits:
          memory: 80M

networks:
  proxy:
    external: true