version: "3.2"

services:

  master:
    image: vfarcic/jenkins:scale-aws
    ports:
      - 50000:50000
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
      - default
    volumes:
      - master:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
        - com.df.alertName=mem_limit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 800M
        limits:
          memory: 1000M
    extra_hosts:
      - "${SLACK_HOST:-devops20.slack.com}:${SLACK_IP:-54.192.78.227}"
    secrets:
      - jenkins-user
      - jenkins-pass

  agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://master:8080/jenkins -labels "prod" -executors 4
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - aws
      - jenkins-user
      - jenkins-pass
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 150M
        limits:
          memory: 300M

networks:
  proxy:
    external: true
  default:
    external: false

secrets:
  aws:
    external: true
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  master:
    driver: cloudstor:aws
    external: false
